feat: add futures + argument serializer
AleoHQ/snarkVM pull request #2404
Opened 2024-03-22 20:09 UTC by miazn

## Motivation

The `Future` and `Argument` structs' serializer/deserializer used the default `collect_str` method, which causes `future` types of Outputs to not convert to proper json, for example when you get a transaction from the REST endpoint it looks like

```  
"outputs": [
    {
      "type": "future",
      "id": "6056862602270631138152110549113103883216888689162817898151691740816207450024field",
      "value": "{\n  program_id: credits.aleo,\n  function_name: transfer_public,\n  arguments: [\n    aleo12z722rd0cyydzazcl5zu22e98yhqj4zs3s6pwqdsl6q04chu8czqtgwyje,\n    aleo1j4jk9243sqcydp0tek7pfnur6a2a7dd7xrfcgqpr2pekgpc9ls9sflvpyy,\n    27000202u64\n  ]\n}"
    }
  ],
```

This PR implements a serialize/deserialize for both the Future and Argument types to enable proper JSON outputs, like:
![image](https://github.com/AleoHQ/snarkVM/assets/93600681/4af90924-f425-49ed-9d6d-8ad6a4e8032e)

## Test Plan

Added serde/bincode tests for the `Future` struct

2024-03-22 21:56 UTC, raychu86 commented
@d0cd Looks like CI is failing due to `A transition output value is missing` errors

2024-03-25 14:19 UTC, miazn commented
Fixed the transition output value, realized that it was still using the `From_str` which was causing a serialize/deserialize issue

2024-03-27 18:12 UTC, howardwu commented
@d0cd, @evan-schott, @ljedrz can you carefully review this PR?

If we add JSON support, we run the risk that the order may matter and need to ensure arrays and types remain consistent in this new design during deserialization.

2024-04-01 08:32 UTC, vicsn commented
Thank you for flagging Howard. This would not have occured to me immediately, but indeed JSON doesn't guarantee ordering. So this PR introduces a UX and security issue because lots of software in the wild may re-order arguments.

Moreover, if we're making changes to serialization, I think we should apply them uniformly across the API, so I would also suggest we also make changes to other objects which have the same almost-but-not-quite JSON problem. A quick scan for `write!(f, "\n` gives me at least: Plaintext Records, Plaintext, Entry, RecordType.

I see the value in using an existing format for communicating our data. Otherwise @unzvfu and other eager users will keep writing custom JSON parsers. Assuming we don't want to go protobuf, we could add an index for fields whose ordering matters.

2024-04-01 11:01 UTC, ljedrz commented
I agree with @vicsn; also, we shouldn't rely on the order of the key-value maps, even if we're using the `preserve_order` feature, for the sake of other implementations.

2024-04-03 20:43 UTC, d0cd requested changes
Left some nits. Overall, the implementation looks good! 

There remains the broader question of using JSON serialization for the other (program-level data types). I see the benefits in using a JSON format, but it does require additional work in standardizing the interface and ensuring that the change does not  negatively impact "programming layers" (Leo and Aleo Instructions). 

Was there a reason why we didn't go with JSON before?

2024-04-03 20:43 UTC, d0cd commented on console/program/src/data/future/serialize.rs
> -    /// Serializes the future into a string or as bytes.
Nit: include the comment.

2024-04-03 20:43 UTC, d0cd commented on console/program/src/data/future/serialize.rs
> -    /// Deserializes the future from a string or bytes.
Nit: include the comment.

2024-04-12 22:04 UTC, howardwu commented
I am still concerned that this breaks the transaction output format. Can anyone confirm? 

Does this change how we pass transaction inputs from CLI at all?

2024-04-17 16:34 UTC, closed without merging

2024-04-17 16:34 UTC, miazn commented
closing for now bc merging this would require a lot of rework