[Feature] new `network.id` opcode
AleoHQ/snarkVM pull request #2419
Opened 2024-04-02 23:15 UTC by evan-schott

## Motivation
This PR introduces the opcode `network.id` to access the ID of the current network (ex: `0` for mainnet, or `3` for testnet3). This opcode can be used as a safeguard against replay attacks, as signatures or hashes of data can now be bound to a specific network. Users can now test program authorizations on testnet without worrying that the same authorizations be maliciously reused on mainnet.

2024-04-02 23:23 UTC, evan-schott commented
Should we add the network ID to the block-specific random seed?
https://github.com/AleoHQ/snarkVM/blob/69b5b17a9d7f32e4f3abbc562ef080adfb654877/synthesizer/program/src/logic/finalize_global_state/mod.rs#L57-L63

2024-04-03 16:40 UTC, d0cd requested changes
Left some feedback and nits.
The main question we should answer is whether or not to allow `network.id` in a non-finalize context.

2024-04-03 16:40 UTC, d0cd commented on ledger/src/tests.rs
> +use console::types::U16;
Nit: move up to L22.

2024-04-03 16:40 UTC, d0cd commented on synthesizer/process/src/stack/evaluate.rs
> +                    Operand::NetworkID => bail!("Cannot retrieve the network ID from a closure scope."),
What is the reason why this shouldn't be available in evaluation?
Same for below.

2024-04-03 16:40 UTC, d0cd commented on synthesizer/process/src/stack/execute.rs
> +                        bail!("Illegal operation: cannot retrieve the network id in a closure scope")
What is the reason why this shouldn't be available in execution?
Same for below.

2024-04-03 16:40 UTC, d0cd commented on synthesizer/process/src/stack/register_types/mod.rs
> +            Operand::NetworkID => bail!("'network.id' is not a valid operand in a non-finalize context."),
Should it be valid?

2024-04-09 21:55 UTC, d0cd commented on synthesizer/process/src/stack/evaluate.rs
> +                    Operand::NetworkID => bail!("Cannot retrieve the network ID from a closure scope."),
Discussed offline. Excluding in execution and evaluation does not prevent the desired use case as you can directly pass in a `u32` and check it against the network in a finalize block.

2024-04-09 21:55 UTC, d0cd commented on synthesizer/process/src/stack/execute.rs
> +                        bail!("Illegal operation: cannot retrieve the network id in a closure scope")
Discussed offline. Excluding in execution and evaluation does not prevent the desired use case as you can directly pass in a u32 and check it against the network in a finalize block.

2024-04-09 21:55 UTC, d0cd commented on synthesizer/process/src/stack/register_types/mod.rs
> +            Operand::NetworkID => bail!("'network.id' is not a valid operand in a non-finalize context."),
Discussed offline. Excluding in execution and evaluation does not prevent the desired use case as you can directly pass in a u32 and check it against the network in a finalize block.

2024-04-09 22:54 UTC, d0cd commented
> Should we add the network ID to the block-specific random seed?
> 
> https://github.com/AleoHQ/snarkVM/blob/69b5b17a9d7f32e4f3abbc562ef080adfb654877/synthesizer/program/src/logic/finalize_global_state/mod.rs#L57-L63

It's not necessary for this PR, but could be a useful property. Networks with different IDs have different RNG state.

2024-04-09 23:12 UTC, d0cd approved these changes

2024-04-12 04:48 UTC, bendyarm approved these changes

2024-04-12 22:47 UTC, merged