Make CI 3x faster
AleoHQ/snarkVM pull request #2484
Opened 2024-06-07 10:18 UTC by vicsn

## Motivation

Already approved and tested here: https://github.com/ProvableHQ/snarkVM/pull/8

2024-06-10 21:19 UTC, zosorock requested changes

2024-06-10 21:19 UTC, zosorock commented on .circleci/config.yml
> +    resource_class: << pipeline.parameters.2xlarge >>
we need to change these from `2xlarge` to `twoxlarge` - here and in other locations (lines 759 and 769)

2024-06-10 21:19 UTC, zosorock commented on .circleci/config.yml
> +    resource_class: << pipeline.parameters.2xlarge >>
we need to change these from `2xlarge` to `twoxlarge`

2024-06-10 21:19 UTC, zosorock commented on .circleci/config.yml
> +    resource_class: << pipeline.parameters.2xlarge >>
we need to change these from `2xlarge` to `twoxlarge`

2024-06-10 23:41 UTC, gluax approved these changes
Still approving for urgency, but how testing is being done should be reconsidered.

2024-06-10 23:41 UTC, gluax commented on synthesizer/program/tests/instruction/assert.rs
> +const ITERATIONS: usize = 25;
These types of tests should be avoided in CI, where we iterate and do random values. These randoms breaks unit and integration test philosophy, and also cause the CI time to increase. Unit tests should try to cover all edge cases, while random/fuzz tests are best done on a dedicated machine off CI. If a random/fuzz test does find something you would then convert it to a unit test.

2024-06-11 01:23 UTC, evanmarshall reviewed
It's not clear to me why any of the values initially existed and why this new value is lower but still sufficiently acceptable. 

Any reason we shouldn't just set them to `1` or `5` or `10`?

2024-06-11 01:50 UTC, Meshiest approved these changes

2024-06-11 05:31 UTC, voximity approved these changes

2024-06-11 05:51 UTC, zosorock approved these changes

2024-06-11 05:51 UTC, merged

2024-06-11 08:47 UTC, vicsn commented
> Any reason we shouldn't just set them to 1 or 5 or 10?

No valid reason, agree with @gluax ' [comment](https://github.com/AleoNet/snarkVM/pull/2484#discussion_r1633980016) and its worth investigating a refactor in the future. Somewhat related: there are some heavy `#[ignore]`'d tests which could potentially also fit in a separate fuzzing / CI / integration testing flow.