[Perf] Don't re-synthesize credits.aleo
AleoHQ/snarkVM pull request #2510
Opened 2024-07-01 19:53 UTC by ljedrz

Closes https://github.com/AleoNet/snarkVM/issues/2416.

2024-07-02 00:31 UTC, raychu86 approved these changes
LGTM, pending CI runs successfully

2024-07-02 18:58 UTC, raychu86 requested changes
This change actually causes the `test_vm_execute_and_finalize` on my machine to hang and never finish. Without the change, it completes in around 8 minutes.

 This should be investigated before we proceed with the changes.

2024-07-03 10:02 UTC, ljedrz commented
I can reproduce this; that being said, I'm not familiar with the associated plumbing so I'm not sure what the nature of the issue is.

2024-07-04 03:20 UTC, vicsn commented
Hmm I can't think immediately of why this would fail. However, given that this optimization is about resynthesis of **proving keys** in `CallStack::Execute` mode, its not something validators run into (who only use CallStack::CheckDeployment), so this seems very low priority

2025-02-17 10:29 UTC, vicsn commented
Closing for now because not a priority to fix. Keeping the issue open.

2025-02-17 10:29 UTC, closed without merging