[Fix] Make deployment verification consistent by deterministically seeding the RNG.
AleoHQ/snarkVM pull request #2535
Opened 2024-08-23 23:32 UTC by d0cd

This PR:
- fixes deployment verification by deterministically seeding the RNG.
- uses explicit wrapping addition in `Fp*::mul_assign` to ensure that tests do not panic. Includes the changes from #2533.

## Failing Case

This issue was found in a deployed program with a similar structure to:
```
program test.aleo;
function foo:
    input r0 as field.private;
    cast r0 into r1 as scalar;
```

At a high-level, deployments are verified by [randomly generating inputs](https://github.com/AleoNet/snarkVM/blob/be171ce0720544c2bc51e27e1674a62fff585adc/synthesizer/process/src/stack/deploy.rs#L107), [executing the program](https://github.com/AleoNet/snarkVM/blob/be171ce0720544c2bc51e27e1674a62fff585adc/synthesizer/process/src/stack/deploy.rs#L161), [extracting the assignment](https://github.com/AleoNet/snarkVM/blob/be171ce0720544c2bc51e27e1674a62fff585adc/synthesizer/process/src/stack/deploy.rs#L165), and [checking that the associated certificates match the structure of the assignment](https://github.com/AleoNet/snarkVM/blob/be171ce0720544c2bc51e27e1674a62fff585adc/algorithms/src/snark/varuna/varuna.rs#L280). **Note that the actual values do not matter. [Source](https://github.com/AleoNet/snarkVM/blob/be171ce0720544c2bc51e27e1674a62fff585adc/algorithms/src/snark/varuna/ahp/indexer/indexer.rs#L135)**

The core issue is that RNG used in generating random inputs can differ across different runs of [verify_deployment](https://github.com/AleoNet/snarkVM/blob/be171ce0720544c2bc51e27e1674a62fff585adc/synthesizer/process/src/stack/deploy.rs#L58).

This manifests in the following way:
1. The execution of `cast r0 into r1 as scalar` creates an invalid scalar field element when `r0` is larger than the scalar field modulus
2. The resulting value is [ejected](https://github.com/AleoNet/snarkVM/blob/be171ce0720544c2bc51e27e1674a62fff585adc/synthesizer/process/src/stack/registers/store.rs#L93) before storing the result into the register `r1` 
3. [Scalar::eject_value](https://github.com/AleoNet/snarkVM/blob/be171ce0720544c2bc51e27e1674a62fff585adc/circuit/types/scalar/src/lib.rs#L75) halts, if the scalar field element is invalid.
Consequently, a deployment of the above program can fail to verify depending on the random inputs that were used. 

## Solution

To fix this issue, this PR deterministically seeds the RNG used in deployment verification with the lower 64 bits of the deployment ID. This ensures that validators will use the same seed for a particular deployment, which ensures that they will always agree on whether the deployment is valid or not.

## Testing

This PR includes a test that attempts to deploy a program that loads and stores data types with invalid scalar field elements. The test verifies that the status of the deployment is consistent: always valid or always invalid, independent of the RNG.

## Considerations

In addition to this PR, additional mitigations can be put in place to ensure that:
- `Scalar::eject_value` does not halt
- Loading and storing circuits to registers does not invoke `eject_value`. This is dependent on whether or not the invocations of `eject_value` are intended to serve as a value check or a less strict type check.

## Related PRs

Use this PR over #2534

2024-08-24 00:54 UTC, MaximizeYourGPU approved these changes
Test rev

2024-08-24 08:36 UTC, vicsn requested changes
I would recommend to **not use** the rng argument at all within `verify_deployment`. The existing assumptions which this PR makes also applies to the `burner_private_key`: its value is not important and if god forbid there's a bug in the key generation code then we'd rather want all validators to abort equally.

In a future PR, we can consider removing the rng argument in `check_next_block` entirely to prevent future developers from introducing non-determinism.

2024-08-24 12:58 UTC, vicsn approved these changes, later dismissed
I would recommend to not use the rng argument at all within verify_deployment. The existing assumptions which this PR makes also applies to the burner_private_key: its value is not important and if god forbid there's a bug in the key generation code then we'd rather want all validators to abort equally.

That being said, this recommendation is not essential, so if we're in a time crunch, we can also leave it for later. In a future PR, we can also consider removing the rng argument in check_next_block entirely to prevent future developers from introducing non-determinism.

2024-08-24 18:36 UTC, zkxuerb approved these changes, later dismissed
LGTM

2024-08-24 18:40 UTC, evanmarshall approved these changes, later dismissed
:shipit:

2024-08-26 22:52 UTC, lukenewman approved these changes
🫡

2024-08-27 06:53 UTC, raychu86 commented
Added a tweak to minimize change-set and clean up the testing; the logic should be equivalent.

Unfortunately this dismissed the previous reviews.

2024-08-27 09:28 UTC, vicsn approved these changes

2024-08-27 09:51 UTC, zkxuerb approved these changes

2024-08-27 13:59 UTC, lukenewman approved these changes

2024-08-27 14:39 UTC, aleojohn approved these changes
LGTM

2024-08-27 15:22 UTC, evanmarshall approved these changes

2024-08-27 16:45 UTC, merged