fix `minimum_tree_size` for `KaryMerkleTree`
AleoHQ/snarkVM pull request #2543
Opened 2024-09-04 02:59 UTC by zhiqiangxu

This issue is not detected because the `leaves` parameter is now ensured to be a power of 8: source .

2024-09-05 14:10 UTC, ljedrz approved these changes
I think this is correct, but I'd recommend double-checking with someone else as well, as I'm a bit rusty with this object.

Also, it would be great if we could have a test proving that the current implementation fails under different assumptions, and that it works correctly with the change in place.

Also, we need a CI run.

2024-09-05 14:25 UTC, zhiqiangxu commented
It seems the CI is out , is there a plan to make it work?

2024-09-05 15:00 UTC, vicsn commented
> This issue is not detected because the leaves parameter is now ensured to be a power of 8

An example calculation for why the issue is currently not triggered would also be appreciated, will help future reviewers

2024-09-05 15:04 UTC, ljedrz reviewed
Overriding the approval to comment mode in order to reflect the request for a test; as for CI runs, those are currently triggered manually by the Foundation.

2024-09-05 15:05 UTC, ljedrz requested changes
Hmm, apparently only "request changes" will override my approval.

2024-09-06 09:27 UTC, zhiqiangxu commented
After further checking, I found that both are correct, but the original code is more memory efficient because of [this logic](https://github.com/AleoNet/snarkVM/blob/02994a1e34e7db8da6c27587537b165aa488868c/console/collections/src/kary_merkle_tree/mod.rs#L128-L133).

2024-09-06 09:27 UTC, closed without merging

2024-09-06 09:55 UTC, ljedrz commented
Thanks for double-checking :pray:!