[Feature] Bits Bytes IR core function
AleoHQ/snarkVM pull request #418
Opened 2021-09-29 19:07 UTC by gluax

## Motivation

To bits and to bytes core function calls in snarkvm for leo.

Right now on the master branch as far as I could tell only implements to_bits and from_bits for integer types. So the core calls exist on the other types to error out for now till those are in. 

## Test Plan

The IR is already thoroughly tested and all tests currently pass.

## Related PRs

Depends on #416 being merged first.

2021-09-29 19:41 UTC, howardwu submitted a review, later dismissed
Before proceeding further on bits and bytes, we need to change convention to `to_bits_le` and `to_bytes_le`, or `_be` if that's what's going on here

2021-09-30 21:28 UTC, collinc97 requested changes

2021-09-30 21:28 UTC, collinc97 commented on eval/src/value/value.rs
> +            Address(_) => Err(anyhow!("the type `address` does not implement the to_bytes method")),
should these error messages read "... to_bits_le method"

2021-09-30 21:28 UTC, collinc97 commented on eval/src/value/value.rs
> +            Address(_) => Err(anyhow!("the type `address` does not implement the to_bytes method")),
similarly "... to_bytes_le method"

2021-09-30 21:40 UTC, collinc97 submitted a review, later dismissed
grammar changes

2021-09-30 21:40 UTC, collinc97 commented on eval/src/value/value.rs
> +            Tuple(_) => Err(anyhow!("the type `tupple` does not implement the to_bits_le method")),
```suggestion
            Tuple(_) => Err(anyhow!("the type `tuple` does not implement the to_bits_le method")),
```

2021-09-30 21:40 UTC, collinc97 commented on eval/src/value/value.rs
> +            Tuple(_) => Err(anyhow!("the type `tupple` does not implement the to_bytes_le method")),
```suggestion
            Tuple(_) => Err(anyhow!("the type `tuple` does not implement the to_bytes_le method")),
```

2021-09-30 21:43 UTC, collinc97 commented
@gluax can we procedurally generate all these methods instead of hard coding them all?
We're expecting ourselves to go back and implement all of these methods at a later date under current assumptions.
But I fear those assumptions may change once we start designing the new programming model for testnet2.

2021-09-30 21:47 UTC, gluax commented
> 
> 
> @gluax can we procedurally generate all these methods instead of hard coding them all? We're expecting ourselves to go back and implement all of these methods at a later date under current assumptions. But I fear those assumptions may change once we start designing the new programming model for testnet2.

We cannot as the function does not have the context to what type it should be outputting at the IR for a generic solution. So we need a method per on the from ones.

2021-10-01 02:26 UTC, 0rphon approved these changes

2021-10-04 20:04 UTC, Protryon commented
Can we use some rust macros to generate the boilerplate rather than making the IR dynamically typed? I.e. like we do for a `Integer` impls in `snarkvm_algorithms`.

2022-04-03 18:37 UTC, closed without merging