Implements absolute value for integer circuit literals
AleoHQ/snarkVM pull request #705
Opened 2022-03-16 05:46 UTC by howardwu

## Motivation

Implements absolute value for integer circuit literals

## Test Plan

Tests the absolute value implementation for all integer types, on all modes.

2022-03-23 18:26 UTC, d0cd requested changes

2022-03-23 18:26 UTC, d0cd commented on circuits/environment/src/traits/integers.rs
> -    macro_rules! checked_impl {
Clean up macros for checked and wrapping impls

2022-03-23 18:26 UTC, d0cd commented on circuits/environment/src/traits/integers.rs
> +        /// Returns the absolute value of the integer type.
Remove `absolute` from `IntegerProperties`

2022-03-23 18:26 UTC, d0cd commented on circuits/types/integers/src/abs_wrapped.rs
> +        // Check the I::MIN (checked) case.
Rename "(checked)" to "(wrapped)"

2022-03-23 18:26 UTC, d0cd commented on circuits/types/integers/src/neg.rs
> +    fn check_neg<I: IntegerType + std::panic::RefUnwindSafe + std::panic::UnwindSafe + Neg<Output = I> >(
May not need RefUnwindSafe, same in AbsWrapped, AbsChecked.

2022-03-26 04:15 UTC, d0cd reviewed
Ready for re-review.

2022-03-26 05:06 UTC, howardwu commented
LGTM

2022-03-26 05:12 UTC, merged